//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.05 at 03:13:40 PM CEST 
//


package eu.vital.reply.xmlpojos;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TaskManager">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Persistence" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   &lt;element name="Visibility" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="HostMode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="MemoryConsumption" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   &lt;element name="AvailMemoryCounter" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   &lt;element name="ProcessMemoryCounter" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   &lt;element name="CPUTotalCounter" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="FreeDiskSpace" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="LastStartTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                   &lt;element name="LogsServiceEndpoint" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="LogsServiceDualBindings" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="LogsPriorityLevel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="LogsTagsList" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="LogsToFile" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="LogsBufferSize" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Thermometer" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Persistence" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   &lt;element name="Visibility" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="HostMode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Owner" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Mobile" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                   &lt;element name="PhysicalLocation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="LogicalLocation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="RFIDTag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="DeviceModel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="DeviceState" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="CurrentValue">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}float">
 *                         &lt;minInclusive value="-20"/>
 *                         &lt;maxInclusive value="100.0"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="IoTSystem">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Persistence" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="Visibility" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="HostMode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Uri" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ServiceArea" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Operator" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="TrafficSensor" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Persistence" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="Visibility" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="HostMode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Mobile" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="PhysicalLocation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="LogicalLocation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="RFIDTag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="DeviceModel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="DeviceState" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="DirectionCount" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="MeasureTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                   &lt;element name="Speed">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}float">
 *                         &lt;minInclusive value="0.0"/>
 *                         &lt;maxInclusive value="200.0"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="Color">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *                         &lt;minInclusive value="0"/>
 *                         &lt;maxInclusive value="4"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="ReverseSpeed">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}float">
 *                         &lt;minInclusive value="0.0"/>
 *                         &lt;maxInclusive value="200.0"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="ReverseColor">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *                         &lt;minInclusive value="0"/>
 *                         &lt;maxInclusive value="4"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "taskManager",
    "thermometer",
    "ioTSystem",
    "trafficSensor"
})
@XmlRootElement(name = "ServiceList")
public class ServiceList {

    @XmlElement(name = "TaskManager", required = true)
    protected ServiceList.TaskManager taskManager;
    @XmlElement(name = "Thermometer")
    protected List<ServiceList.Thermometer> thermometer;
    @XmlElement(name = "IoTSystem", required = true)
    protected ServiceList.IoTSystem ioTSystem;
    @XmlElement(name = "TrafficSensor")
    protected List<ServiceList.TrafficSensor> trafficSensor;

    /**
     * Gets the value of the taskManager property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceList.TaskManager }
     *     
     */
    public ServiceList.TaskManager getTaskManager() {
        return taskManager;
    }

    /**
     * Sets the value of the taskManager property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceList.TaskManager }
     *     
     */
    public void setTaskManager(ServiceList.TaskManager value) {
        this.taskManager = value;
    }

    /**
     * Gets the value of the thermometer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the thermometer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getThermometer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ServiceList.Thermometer }
     * 
     * 
     */
    public List<ServiceList.Thermometer> getThermometer() {
        if (thermometer == null) {
            thermometer = new ArrayList<ServiceList.Thermometer>();
        }
        return this.thermometer;
    }

    /**
     * Gets the value of the ioTSystem property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceList.IoTSystem }
     *     
     */
    public ServiceList.IoTSystem getIoTSystem() {
        return ioTSystem;
    }

    /**
     * Sets the value of the ioTSystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceList.IoTSystem }
     *     
     */
    public void setIoTSystem(ServiceList.IoTSystem value) {
        this.ioTSystem = value;
    }

    /**
     * Gets the value of the trafficSensor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the trafficSensor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTrafficSensor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ServiceList.TrafficSensor }
     * 
     * 
     */
    public List<ServiceList.TrafficSensor> getTrafficSensor() {
        if (trafficSensor == null) {
            trafficSensor = new ArrayList<ServiceList.TrafficSensor>();
        }
        return this.trafficSensor;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Persistence" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="Visibility" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="HostMode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Uri" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ServiceArea" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Operator" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "description",
        "persistence",
        "visibility",
        "hostMode",
        "uri",
        "serviceArea",
        "operator",
        "status"
    })
    public static class IoTSystem {

        @XmlElement(name = "ID", required = true)
        protected String id;
        @XmlElement(name = "Description", required = true)
        protected String description;
        @XmlElement(name = "Persistence")
        protected byte persistence;
        @XmlElement(name = "Visibility", required = true)
        protected String visibility;
        @XmlElement(name = "HostMode", required = true)
        protected String hostMode;
        @XmlElement(name = "Uri", required = true)
        protected String uri;
        @XmlElement(name = "ServiceArea", required = true)
        protected String serviceArea;
        @XmlElement(name = "Operator", required = true)
        protected String operator;
        @XmlElement(name = "Status", required = true)
        protected String status;

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getID() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setID(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescription(String value) {
            this.description = value;
        }

        /**
         * Gets the value of the persistence property.
         * 
         */
        public byte getPersistence() {
            return persistence;
        }

        /**
         * Sets the value of the persistence property.
         * 
         */
        public void setPersistence(byte value) {
            this.persistence = value;
        }

        /**
         * Gets the value of the visibility property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVisibility() {
            return visibility;
        }

        /**
         * Sets the value of the visibility property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVisibility(String value) {
            this.visibility = value;
        }

        /**
         * Gets the value of the hostMode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHostMode() {
            return hostMode;
        }

        /**
         * Sets the value of the hostMode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHostMode(String value) {
            this.hostMode = value;
        }

        /**
         * Gets the value of the uri property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUri() {
            return uri;
        }

        /**
         * Sets the value of the uri property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUri(String value) {
            this.uri = value;
        }

        /**
         * Gets the value of the serviceArea property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getServiceArea() {
            return serviceArea;
        }

        /**
         * Sets the value of the serviceArea property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setServiceArea(String value) {
            this.serviceArea = value;
        }

        /**
         * Gets the value of the operator property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOperator() {
            return operator;
        }

        /**
         * Sets the value of the operator property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOperator(String value) {
            this.operator = value;
        }

        /**
         * Gets the value of the status property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStatus() {
            return status;
        }

        /**
         * Sets the value of the status property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStatus(String value) {
            this.status = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Persistence" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="Visibility" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="HostMode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="MemoryConsumption" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="AvailMemoryCounter" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="ProcessMemoryCounter" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="CPUTotalCounter" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *         &lt;element name="FreeDiskSpace" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="LastStartTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *         &lt;element name="LogsServiceEndpoint" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="LogsServiceDualBindings" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="LogsPriorityLevel" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="LogsTagsList" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="LogsToFile" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="LogsBufferSize" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "description",
        "persistence",
        "visibility",
        "hostMode",
        "memoryConsumption",
        "availMemoryCounter",
        "processMemoryCounter",
        "cpuTotalCounter",
        "freeDiskSpace",
        "lastStartTime",
        "logsServiceEndpoint",
        "logsServiceDualBindings",
        "logsPriorityLevel",
        "logsTagsList",
        "logsToFile",
        "logsBufferSize"
    })
    public static class TaskManager {

        @XmlElement(name = "ID", required = true)
        protected String id;
        @XmlElement(name = "Description", required = true)
        protected String description;
        @XmlElement(name = "Persistence", required = true)
        protected BigInteger persistence;
        @XmlElement(name = "Visibility", required = true)
        protected String visibility;
        @XmlElement(name = "HostMode", required = true)
        protected String hostMode;
        @XmlElement(name = "MemoryConsumption", required = true)
        protected BigInteger memoryConsumption;
        @XmlElement(name = "AvailMemoryCounter", required = true)
        protected BigInteger availMemoryCounter;
        @XmlElement(name = "ProcessMemoryCounter", required = true)
        protected BigInteger processMemoryCounter;
        @XmlElement(name = "CPUTotalCounter")
        protected float cpuTotalCounter;
        @XmlElement(name = "FreeDiskSpace", required = true)
        protected String freeDiskSpace;
        @XmlElement(name = "LastStartTime", required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar lastStartTime;
        @XmlElement(name = "LogsServiceEndpoint", required = true)
        protected String logsServiceEndpoint;
        @XmlElement(name = "LogsServiceDualBindings", required = true)
        protected String logsServiceDualBindings;
        @XmlElement(name = "LogsPriorityLevel", required = true)
        protected String logsPriorityLevel;
        @XmlElement(name = "LogsTagsList", required = true)
        protected String logsTagsList;
        @XmlElement(name = "LogsToFile", required = true)
        protected String logsToFile;
        @XmlElement(name = "LogsBufferSize", required = true)
        protected BigInteger logsBufferSize;

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getID() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setID(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescription(String value) {
            this.description = value;
        }

        /**
         * Gets the value of the persistence property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getPersistence() {
            return persistence;
        }

        /**
         * Sets the value of the persistence property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setPersistence(BigInteger value) {
            this.persistence = value;
        }

        /**
         * Gets the value of the visibility property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVisibility() {
            return visibility;
        }

        /**
         * Sets the value of the visibility property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVisibility(String value) {
            this.visibility = value;
        }

        /**
         * Gets the value of the hostMode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHostMode() {
            return hostMode;
        }

        /**
         * Sets the value of the hostMode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHostMode(String value) {
            this.hostMode = value;
        }

        /**
         * Gets the value of the memoryConsumption property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getMemoryConsumption() {
            return memoryConsumption;
        }

        /**
         * Sets the value of the memoryConsumption property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setMemoryConsumption(BigInteger value) {
            this.memoryConsumption = value;
        }

        /**
         * Gets the value of the availMemoryCounter property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getAvailMemoryCounter() {
            return availMemoryCounter;
        }

        /**
         * Sets the value of the availMemoryCounter property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setAvailMemoryCounter(BigInteger value) {
            this.availMemoryCounter = value;
        }

        /**
         * Gets the value of the processMemoryCounter property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getProcessMemoryCounter() {
            return processMemoryCounter;
        }

        /**
         * Sets the value of the processMemoryCounter property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setProcessMemoryCounter(BigInteger value) {
            this.processMemoryCounter = value;
        }

        /**
         * Gets the value of the cpuTotalCounter property.
         * 
         */
        public float getCPUTotalCounter() {
            return cpuTotalCounter;
        }

        /**
         * Sets the value of the cpuTotalCounter property.
         * 
         */
        public void setCPUTotalCounter(float value) {
            this.cpuTotalCounter = value;
        }

        /**
         * Gets the value of the freeDiskSpace property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFreeDiskSpace() {
            return freeDiskSpace;
        }

        /**
         * Sets the value of the freeDiskSpace property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFreeDiskSpace(String value) {
            this.freeDiskSpace = value;
        }

        /**
         * Gets the value of the lastStartTime property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getLastStartTime() {
            return lastStartTime;
        }

        /**
         * Sets the value of the lastStartTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setLastStartTime(XMLGregorianCalendar value) {
            this.lastStartTime = value;
        }

        /**
         * Gets the value of the logsServiceEndpoint property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLogsServiceEndpoint() {
            return logsServiceEndpoint;
        }

        /**
         * Sets the value of the logsServiceEndpoint property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLogsServiceEndpoint(String value) {
            this.logsServiceEndpoint = value;
        }

        /**
         * Gets the value of the logsServiceDualBindings property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLogsServiceDualBindings() {
            return logsServiceDualBindings;
        }

        /**
         * Sets the value of the logsServiceDualBindings property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLogsServiceDualBindings(String value) {
            this.logsServiceDualBindings = value;
        }

        /**
         * Gets the value of the logsPriorityLevel property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLogsPriorityLevel() {
            return logsPriorityLevel;
        }

        /**
         * Sets the value of the logsPriorityLevel property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLogsPriorityLevel(String value) {
            this.logsPriorityLevel = value;
        }

        /**
         * Gets the value of the logsTagsList property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLogsTagsList() {
            return logsTagsList;
        }

        /**
         * Sets the value of the logsTagsList property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLogsTagsList(String value) {
            this.logsTagsList = value;
        }

        /**
         * Gets the value of the logsToFile property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLogsToFile() {
            return logsToFile;
        }

        /**
         * Sets the value of the logsToFile property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLogsToFile(String value) {
            this.logsToFile = value;
        }

        /**
         * Gets the value of the logsBufferSize property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getLogsBufferSize() {
            return logsBufferSize;
        }

        /**
         * Sets the value of the logsBufferSize property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setLogsBufferSize(BigInteger value) {
            this.logsBufferSize = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Persistence" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="Visibility" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="HostMode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Owner" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Mobile" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *         &lt;element name="PhysicalLocation" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="LogicalLocation" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="RFIDTag" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="DeviceModel" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="DeviceState" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="CurrentValue">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}float">
     *               &lt;minInclusive value="-20"/>
     *               &lt;maxInclusive value="100.0"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "description",
        "persistence",
        "visibility",
        "hostMode",
        "owner",
        "mobile",
        "physicalLocation",
        "logicalLocation",
        "rfidTag",
        "deviceModel",
        "deviceState",
        "currentValue"
    })
    public static class Thermometer {

        @XmlElement(name = "ID", required = true)
        protected String id;
        @XmlElement(name = "Description", required = true)
        protected String description;
        @XmlElement(name = "Persistence", required = true)
        protected BigInteger persistence;
        @XmlElement(name = "Visibility", required = true)
        protected String visibility;
        @XmlElement(name = "HostMode", required = true)
        protected String hostMode;
        @XmlElement(name = "Owner", required = true)
        protected String owner;
        @XmlElement(name = "Mobile")
        protected boolean mobile;
        @XmlElement(name = "PhysicalLocation", required = true)
        protected String physicalLocation;
        @XmlElement(name = "LogicalLocation", required = true)
        protected String logicalLocation;
        @XmlElement(name = "RFIDTag", required = true)
        protected String rfidTag;
        @XmlElement(name = "DeviceModel", required = true)
        protected String deviceModel;
        @XmlElement(name = "DeviceState", required = true)
        protected String deviceState;
        @XmlElement(name = "CurrentValue")
        protected float currentValue;

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getID() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setID(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescription(String value) {
            this.description = value;
        }

        /**
         * Gets the value of the persistence property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getPersistence() {
            return persistence;
        }

        /**
         * Sets the value of the persistence property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setPersistence(BigInteger value) {
            this.persistence = value;
        }

        /**
         * Gets the value of the visibility property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVisibility() {
            return visibility;
        }

        /**
         * Sets the value of the visibility property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVisibility(String value) {
            this.visibility = value;
        }

        /**
         * Gets the value of the hostMode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHostMode() {
            return hostMode;
        }

        /**
         * Sets the value of the hostMode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHostMode(String value) {
            this.hostMode = value;
        }

        /**
         * Gets the value of the owner property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOwner() {
            return owner;
        }

        /**
         * Sets the value of the owner property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOwner(String value) {
            this.owner = value;
        }

        /**
         * Gets the value of the mobile property.
         * 
         */
        public boolean isMobile() {
            return mobile;
        }

        /**
         * Sets the value of the mobile property.
         * 
         */
        public void setMobile(boolean value) {
            this.mobile = value;
        }

        /**
         * Gets the value of the physicalLocation property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPhysicalLocation() {
            return physicalLocation;
        }

        /**
         * Sets the value of the physicalLocation property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPhysicalLocation(String value) {
            this.physicalLocation = value;
        }

        /**
         * Gets the value of the logicalLocation property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLogicalLocation() {
            return logicalLocation;
        }

        /**
         * Sets the value of the logicalLocation property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLogicalLocation(String value) {
            this.logicalLocation = value;
        }

        /**
         * Gets the value of the rfidTag property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRFIDTag() {
            return rfidTag;
        }

        /**
         * Sets the value of the rfidTag property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRFIDTag(String value) {
            this.rfidTag = value;
        }

        /**
         * Gets the value of the deviceModel property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDeviceModel() {
            return deviceModel;
        }

        /**
         * Sets the value of the deviceModel property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDeviceModel(String value) {
            this.deviceModel = value;
        }

        /**
         * Gets the value of the deviceState property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDeviceState() {
            return deviceState;
        }

        /**
         * Sets the value of the deviceState property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDeviceState(String value) {
            this.deviceState = value;
        }

        /**
         * Gets the value of the currentValue property.
         * 
         */
        public float getCurrentValue() {
            return currentValue;
        }

        /**
         * Sets the value of the currentValue property.
         * 
         */
        public void setCurrentValue(float value) {
            this.currentValue = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Persistence" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="Visibility" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="HostMode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Mobile" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="PhysicalLocation" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="LogicalLocation" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="RFIDTag" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="DeviceModel" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="DeviceState" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="DirectionCount" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="MeasureTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *         &lt;element name="Speed">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}float">
     *               &lt;minInclusive value="0.0"/>
     *               &lt;maxInclusive value="200.0"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="Color">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
     *               &lt;minInclusive value="0"/>
     *               &lt;maxInclusive value="4"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="ReverseSpeed">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}float">
     *               &lt;minInclusive value="0.0"/>
     *               &lt;maxInclusive value="200.0"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="ReverseColor">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
     *               &lt;minInclusive value="0"/>
     *               &lt;maxInclusive value="4"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "description",
        "persistence",
        "visibility",
        "hostMode",
        "mobile",
        "physicalLocation",
        "logicalLocation",
        "rfidTag",
        "deviceModel",
        "deviceState",
        "directionCount",
        "status",
        "measureTime",
        "speed",
        "color",
        "reverseSpeed",
        "reverseColor"
    })
    public static class TrafficSensor {

        @XmlElement(name = "ID", required = true)
        protected String id;
        @XmlElement(name = "Description", required = true)
        protected String description;
        @XmlElement(name = "Persistence")
        protected byte persistence;
        @XmlElement(name = "Visibility", required = true)
        protected String visibility;
        @XmlElement(name = "HostMode", required = true)
        protected String hostMode;
        @XmlElement(name = "Mobile", required = true)
        protected String mobile;
        @XmlElement(name = "PhysicalLocation", required = true)
        protected String physicalLocation;
        @XmlElement(name = "LogicalLocation", required = true)
        protected String logicalLocation;
        @XmlElement(name = "RFIDTag", required = true)
        protected String rfidTag;
        @XmlElement(name = "DeviceModel", required = true)
        protected String deviceModel;
        @XmlElement(name = "DeviceState", required = true)
        protected String deviceState;
        @XmlElement(name = "DirectionCount")
        protected byte directionCount;
        @XmlElement(name = "Status")
        protected byte status;
        @XmlElement(name = "MeasureTime", required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar measureTime;
        @XmlElement(name = "Speed")
        protected float speed;
        @XmlElement(name = "Color")
        protected int color;
        @XmlElement(name = "ReverseSpeed")
        protected float reverseSpeed;
        @XmlElement(name = "ReverseColor")
        protected int reverseColor;

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getID() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setID(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescription(String value) {
            this.description = value;
        }

        /**
         * Gets the value of the persistence property.
         * 
         */
        public byte getPersistence() {
            return persistence;
        }

        /**
         * Sets the value of the persistence property.
         * 
         */
        public void setPersistence(byte value) {
            this.persistence = value;
        }

        /**
         * Gets the value of the visibility property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVisibility() {
            return visibility;
        }

        /**
         * Sets the value of the visibility property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVisibility(String value) {
            this.visibility = value;
        }

        /**
         * Gets the value of the hostMode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHostMode() {
            return hostMode;
        }

        /**
         * Sets the value of the hostMode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHostMode(String value) {
            this.hostMode = value;
        }

        /**
         * Gets the value of the mobile property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMobile() {
            return mobile;
        }

        /**
         * Sets the value of the mobile property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMobile(String value) {
            this.mobile = value;
        }

        /**
         * Gets the value of the physicalLocation property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPhysicalLocation() {
            return physicalLocation;
        }

        /**
         * Sets the value of the physicalLocation property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPhysicalLocation(String value) {
            this.physicalLocation = value;
        }

        /**
         * Gets the value of the logicalLocation property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLogicalLocation() {
            return logicalLocation;
        }

        /**
         * Sets the value of the logicalLocation property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLogicalLocation(String value) {
            this.logicalLocation = value;
        }

        /**
         * Gets the value of the rfidTag property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRFIDTag() {
            return rfidTag;
        }

        /**
         * Sets the value of the rfidTag property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRFIDTag(String value) {
            this.rfidTag = value;
        }

        /**
         * Gets the value of the deviceModel property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDeviceModel() {
            return deviceModel;
        }

        /**
         * Sets the value of the deviceModel property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDeviceModel(String value) {
            this.deviceModel = value;
        }

        /**
         * Gets the value of the deviceState property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDeviceState() {
            return deviceState;
        }

        /**
         * Sets the value of the deviceState property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDeviceState(String value) {
            this.deviceState = value;
        }

        /**
         * Gets the value of the directionCount property.
         * 
         */
        public byte getDirectionCount() {
            return directionCount;
        }

        /**
         * Sets the value of the directionCount property.
         * 
         */
        public void setDirectionCount(byte value) {
            this.directionCount = value;
        }

        /**
         * Gets the value of the status property.
         * 
         */
        public byte getStatus() {
            return status;
        }

        /**
         * Sets the value of the status property.
         * 
         */
        public void setStatus(byte value) {
            this.status = value;
        }

        /**
         * Gets the value of the measureTime property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getMeasureTime() {
            return measureTime;
        }

        /**
         * Sets the value of the measureTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setMeasureTime(XMLGregorianCalendar value) {
            this.measureTime = value;
        }

        /**
         * Gets the value of the speed property.
         * 
         */
        public float getSpeed() {
            return speed;
        }

        /**
         * Sets the value of the speed property.
         * 
         */
        public void setSpeed(float value) {
            this.speed = value;
        }

        /**
         * Gets the value of the color property.
         * 
         */
        public int getColor() {
            return color;
        }

        /**
         * Sets the value of the color property.
         * 
         */
        public void setColor(int value) {
            this.color = value;
        }

        /**
         * Gets the value of the reverseSpeed property.
         * 
         */
        public float getReverseSpeed() {
            return reverseSpeed;
        }

        /**
         * Sets the value of the reverseSpeed property.
         * 
         */
        public void setReverseSpeed(float value) {
            this.reverseSpeed = value;
        }

        /**
         * Gets the value of the reverseColor property.
         * 
         */
        public int getReverseColor() {
            return reverseColor;
        }

        /**
         * Sets the value of the reverseColor property.
         * 
         */
        public void setReverseColor(int value) {
            this.reverseColor = value;
        }

    }

}
